# 储存数据集的路径
data:
  dataset: 'MIMII'
  file_path: './data/data.pkl'
  batch_size: 32
  test_size: 0.2
  random_seed: 42
# 模型
model:
  model: 'CNN'
  input_dim: 1
  hidden_dim: 128
  output_dim: 2
  length: 313
# 训练参数
train:
  epoches: 100
  loss: 'CrossEntropyLoss'
optimizer:
  optim: 'Adam'
  lr: 0.00001

model_save_dir: 'output'