data:
  dataset: 'MIMII'
  file_path: './data/data.pkl'
  batch_size: 32
  test_size: 0.2
  random_seed: 42
model:
  model: 'DenseNet'
  input_dim: 1        
  num_init_features: 32       # 初始通道32（适配128x128输入）
  block_config: [4,4,4]       # 3个DenseBlock，每个4层（轻量版）
  batchnorm_size: 4           # Bottleneck倍数4
  growth_rate: 12             # 增长率12
  drop_rate: 0.2              # Dropout 20%
  compression_rate: 0.5       # 压缩率50%
  num_classes: 2
# 训练参数
train:
  epoches: 100
  loss: 'CrossEntropyLoss'
optimizer:
  optim: 'Adam'
  lr: 0.00001
model_save_dir: 'output'
